spring:
    datasource:
      url: jdbc:postgresql://ep-small-snowflake-a2g59h2p.eu-central-1.pg.koyeb.app/txt_master
      username: koyeb-adm
      password: 6p0EnKQiFbxs
      driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect 
      show-sql: true
      hibernate:
        ddl-auto: update
      
server:
  port: 15000                                    
